name: data-analysis-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.11
  - pip>=23.0
  - jupyterlab>=4.0
  - pandas>=2.0
  - numpy>=1.24
  - scikit-learn>=1.3
  - statsmodels>=0.14.0
  - matplotlib>=3.7
  - seaborn>=0.12
  - dvc>=3.0
  - dvc-s3>=3.0
  - botocore<1.36.0
  - boto3<1.36.0
  - pip:
      - black>=23.0
      - ruff>=0.1
      - yfinance>=0.2.0
      - gridstatus>=0.35.0
      - sec-edgar-downloader>=5.1.0
      - xgboost>=2.0.0
      - pre-commit>=3.6.0
      - nbstripout>=0.7.1
      