#!/bin/bash
set -e

# =============================================================================
# deploy_to_colab.sh
#
# Reads secrets from .env + GCP ADC, generates self-contained pipeline runner,
# deploys to a fresh Colab VM via `colab run`, auto-releases on completion.
#
# Usage:
#   ./deploy_to_colab.sh
#
# Prerequisites:
#   - colab CLI installed (pip install colab-cli)
#   - GCP ADC configured (gcloud auth application-default login)
#   - .env file with: CENSUS_API_KEY, FRED_API_KEY,
#     (AWS_ACCESS_KEY_ID|OCI_ACCESS_KEY), (AWS_SECRET_ACCESS_KEY|OCI_SECRET_KEY)
#   - Optional: GH_TOKEN (for private repo clone),
#     GOOGLE_CLOUD_PROJECT (extracted from ADC if omitted)
# =============================================================================

echo "=== Generating colab pipeline runner ==="

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
DOTENV="$REPO_DIR/.env"

if [ ! -f "$DOTENV" ]; then
  echo "ERROR: .env not found at $DOTENV"
  exit 1
fi

# Source .env (exports all vars)
set -a
source "$DOTENV"
set +a

# Generate the self-contained runner script via Python
# (Python handles complex string escaping that bash cannot)
python3 << 'PYEOF'
import os, sys, json, base64, platform, textwrap
from pathlib import Path

REPO_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) if "__file__" in dir() else os.getcwd()

def log(msg):
    print(f"  {msg}", flush=True)

# ---------------------------------------------------------------------------
# 1. Collect secrets from environment
# ---------------------------------------------------------------------------
secrets = {}

# GCP ADC credentials
adc_path_candidates = []
env_adc = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS", "")
if env_adc:
    adc_path_candidates.append(env_adc)
adc_path_candidates.append(os.path.expanduser("~/.config/gcloud/application_default_credentials.json"))

adc_path = None
for p in adc_path_candidates:
    if os.path.exists(p):
        adc_path = p
        break

if not adc_path:
    log("ERROR: GCP ADC credentials not found")
    log("  Tried:")
    for p in adc_path_candidates:
        log(f"    {p}")
    log("  Run: gcloud auth application-default login")
    sys.exit(1)

with open(adc_path, "rb") as f:
    adc_bytes = f.read()
    adc_data = json.loads(adc_bytes)
    secrets["gcp_adc_b64"] = base64.b64encode(adc_bytes).decode()

log(f"GCP ADC loaded from: {adc_path}")

# GOOGLE_CLOUD_PROJECT — from env, or extract from ADC
gcp_project = os.environ.get("GOOGLE_CLOUD_PROJECT", "")
if not gcp_project:
    gcp_project = adc_data.get("quota_project_id", adc_data.get("project_id", ""))
secrets["GOOGLE_CLOUD_PROJECT"] = gcp_project
log(f"GOOGLE_CLOUD_PROJECT: {gcp_project or '(empty — step12 will extract from ADC)'}")

# Census API key
census_key = os.environ.get("CENSUS_API_KEY", "")
if not census_key:
    log("WARN: CENSUS_API_KEY not set")
secrets["CENSUS_API_KEY"] = census_key

# FRED API key
fred_key = os.environ.get("FRED_API_KEY", "")
if not fred_key:
    log("WARN: FRED_API_KEY not set")
secrets["FRED_API_KEY"] = fred_key

# OCI keys — check both AWS_ and OCI_ prefixed names (the .env uses AWS_ prefix)
oci_key = os.environ.get("OCI_ACCESS_KEY", os.environ.get("AWS_ACCESS_KEY_ID", ""))
oci_secret = os.environ.get("OCI_SECRET_KEY", os.environ.get("AWS_SECRET_ACCESS_KEY", ""))
if not oci_key or not oci_secret:
    log("ERROR: OCI credentials not found")
    log("  Set OCI_ACCESS_KEY and OCI_SECRET_KEY (or AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY)")
    sys.exit(1)
secrets["OCI_ACCESS_KEY"] = oci_key
secrets["OCI_SECRET_KEY"] = oci_secret
log(f"OCI_ACCESS_KEY: {'set' if oci_key else 'missing'}")
log(f"OCI_SECRET_KEY: {'set' if oci_secret else 'missing'}")

# GH_TOKEN (optional — repo is public)
gh_token = os.environ.get("GH_TOKEN", os.environ.get("GITHUB_TOKEN", ""))
if gh_token:
    secrets["GH_TOKEN"] = gh_token
    log("GH_TOKEN: set (authenticated clone)")
else:
    log("GH_TOKEN: not set (public clone — OK for public repo)")

# Encode secrets as base64 JSON for embedding in runner
secrets_json = json.dumps(secrets, indent=2)
secrets_b64 = base64.b64encode(secrets_json.encode()).decode()
log(f"Secrets encoded: {len(secrets_b64)} bytes")

# ---------------------------------------------------------------------------
# 2. Build the runner script template
# ---------------------------------------------------------------------------
runner_template = '''#!/usr/bin/env python3
"""
Self-contained Colab pipeline runner.
Generated by deploy_to_colab.sh — secrets embedded at generation time.
Runs steps 12 (GDELT BQ query) + 13 (article extraction) + 14 (gridstatus).
"""
import os, sys, json, base64, subprocess, time, traceback
from pathlib import Path

# --- EMBEDDED SECRETS (base64-encoded JSON) ---
# Generated: __GENERATED_AT__
SECRETS_B64 = \"\"\"__SECRETS_B64__\"\"\"

REPO_URL = "https://github.com/Aidas-dev/computer-data-analysis-report.git"
REPO_DIR = "/content/computer-data-analysis-report"


def log(msg):
    print(f"[pipeline] {msg}", flush=True)


def run(cmd, timeout=600, check=True):
    \"\"\"Run shell command, stream stdout, raise on failure.\"\"\"
    log(f"$ {cmd[:150]}")
    r = subprocess.run(
        cmd, shell=True, timeout=timeout,
        capture_output=True, text=True
    )
    for line in r.stdout.strip().split("\\n"):
        if line:
            print(f"  {line}", flush=True)
    if check and r.returncode != 0:
        for line in r.stderr.strip().split("\\n")[-5:]:
            if line:
                print(f"  ERR: {line}", flush=True)
        raise RuntimeError(
            f"FAIL (rc={r.returncode}): {cmd[:80]}"
        )
    return r


def main():
    log("=== Pipeline: Colab Runner ===")
    log(f"Python: {sys.version.split()[0]}")

    # ---- Decode secrets ----
    secrets = json.loads(base64.b64decode(SECRETS_B64).decode())
    gcp_adc_data = json.loads(base64.b64decode(secrets["gcp_adc_b64"]).decode())

    # ---- Write ADC credentials ----
    Path("/content/gcp_adc.json").write_text(
        json.dumps(gcp_adc_data, indent=2)
    )
    os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/content/gcp_adc.json"
    os.environ["GOOGLE_CLOUD_PROJECT"] = secrets.get(
        "GOOGLE_CLOUD_PROJECT",
        gcp_adc_data.get("quota_project_id", gcp_adc_data.get("project_id", ""))
    )
    os.environ["CENSUS_API_KEY"] = secrets.get("CENSUS_API_KEY", "")
    os.environ["FRED_API_KEY"] = secrets.get("FRED_API_KEY", "")
    log("Secrets decoded. Env vars set.")

    # ---- Install dependencies ----
    log("=== Installing dependencies ===")
    run("pip install uv -q", timeout=30)
    run(
        "uv pip install --system "
        "google-cloud-bigquery pandas trafilatura newspaper3k "
        "lxml_html_clean gridstatus -q",
        timeout=300,
    )
    run("uv pip install --system dvc dvc[s3] -q", timeout=120)
    log("Deps installed.")

    # ---- Clone / pull repository ----
    log("=== Cloning repository ===")
    gh_token = secrets.get("GH_TOKEN", "")
    if gh_token:
        auth_url = (
            f"https://{gh_token}@github.com/"
            "Aidas-dev/computer-data-analysis-report.git"
        )
        log("Using authenticated clone (GH_TOKEN)")
    else:
        auth_url = REPO_URL
        log("Using public clone")
    if Path(REPO_DIR).exists():
        run(f"git -C {REPO_DIR} pull --ff-only", timeout=60)
    else:
        run(f"git clone --depth 1 {auth_url} {REPO_DIR}", timeout=120)
    os.chdir(REPO_DIR)
    log(f"Working dir: {os.getcwd()}")

    # Also write ADC to docs/ (step12 checks this path too)
    Path("docs/gcp_adc.json").write_text(
        json.dumps(gcp_adc_data, indent=2)
    )
    log("ADC credentials written to /content/gcp_adc.json and docs/gcp_adc.json")

    # ---- Configure DVC remote ----
    log("=== DVC setup ===")
    oci_key = secrets.get("OCI_ACCESS_KEY", "")
    oci_secret = secrets.get("OCI_SECRET_KEY", "")
    if not oci_key or not oci_secret:
        log("ERROR: OCI credentials missing in secrets")
        sys.exit(1)
    run(
        f"dvc remote modify --local oracle_remote "
        f"access_key_id '{oci_key}'"
    )
    run(
        f"dvc remote modify --local oracle_remote "
        f"secret_access_key '{oci_secret}'"
    )
    run("dvc pull -q", timeout=300)
    log("DVC data pulled.")

    # ---- Run pipeline steps ----
    # Check if step12 output already exists (from DVC pull)
    step12_done = Path("data/raw/buildout_candidates_gkg.csv").exists()
    steps = []
    if not step12_done:
        steps.append((12, "scripts/pipeline_step12.py"))
    else:
        log("Step 12 output exists — skipping BQ query")
    steps += [(13, "scripts/pipeline_step13.py"), (14, "scripts/pipeline_step14.py")]

    results = {}
    for num, script_path in steps:
        log(f"=== Step {num}: {script_path} ===")
        marker = Path(f"/tmp/done_pipeline_step{num}")
        marker.unlink(missing_ok=True)
        t0 = time.time()
        try:
            run(f"python3 {script_path}", timeout=3600)
            elapsed = time.time() - t0
            log(f"[pipeline] Step {num} OK ({elapsed:.0f}s)")
            results[num] = True
        except Exception as e:
            elapsed = time.time() - t0
            log(
                f"[pipeline] Step {num} FAILED after {elapsed:.0f}s: {e}"
            )
            results[num] = False

    # ---- DVC push ----
    log("=== DVC Push ===")
    try:
        run("dvc push -q", timeout=300)
        log("DVC push OK")
    except Exception as e:
        log(f"DVC push FAIL: {e}")

    # ---- Summary ----
    log("=== PIPELINE SUMMARY ===")
    all_ok = True
    for num in [12, 13, 14]:
        ok = results.get(num, False)
        log(f"  Step {num}: {'OK' if ok else 'FAIL'}")
        if not ok:
            all_ok = False

    if all_ok:
        log("PIPELINE COMPLETE")
    else:
        log("PIPELINE COMPLETE (with failures)")
        sys.exit(1)


if __name__ == "__main__":
    main()
'''

# Embed the timestamp and secrets
from datetime import datetime
generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
runner_script = (
    runner_template
    .replace("__GENERATED_AT__", generated_at)
    .replace("__SECRETS_B64__", secrets_b64)
)

# Write runner to /tmp/
output_path = "/tmp/colab_run_pipeline.py"
with open(output_path, "w") as f:
    f.write(runner_script)
os.chmod(output_path, 0o755)

log(f"Runner script written: {output_path}")
log(f"Size: {len(runner_script)} bytes")

# Quick syntax check
try:
    compile(runner_script, output_path, "exec")
    log("Syntax check: OK")
except SyntaxError as e:
    log(f"ERROR: Syntax error in generated runner: {e}")
    sys.exit(1)

log("Secrets embedded: " + ", ".join(
    k for k in secrets.keys()
))
PYEOF

echo "=== Deploying to colab ==="
echo "  Session: pipeline-run"
echo "  Script:  /tmp/colab_run_pipeline.py"

colab run -s pipeline-run /tmp/colab_run_pipeline.py

echo "=== Pipeline deployment complete ==="
